export const menCharacters = [
  {
    id: 0,
    name: "Groot",
    url: "../assets/characters/men/groot.png",
    bio: "I am Groot",
  },
  {
    id: 1,
    name: "Yoda",
    url: "../assets/characters/men/yoda.png",
    bio: "Size matters not, but swipe right, you must",
  },
  {
    id: 2,
    name: "Forrest Gump",
    url: "../assets/characters/men/forrest.png",
    bio: "I'm a former college football player, shrimp boat captain, and Vietnam veteran. Seeking someone who can appreciate my love of running and Ping-Pong. I may not be a smart man, but I know what love is.",
  },
  {
    id: 3,
    name: "Mclovin",
    url: "../assets/characters/men/mclovin.png",
    bio: "Hawain. Organ donor",
  },
  {
    id: 4,
    name: "Borat Sagdiyev",
    url: "../assets/characters/men/borat.png",
    bio: "Kazakh journalist and world traveler seeking partner for cultural exchange and sexy time.",
  },
  {
    id: 5,
    name: "Joey Tribbiani",
    url: "../assets/characters/men/joey.png",
    bio: "Hey, How you doin'? I'm an actor and I speak French fluently. Let's go get food (I don't share).",
  },
  {
    id: 6,
    name: "Jason Voorhees",
    url: "../assets/characters/men/jason.png",
    bio: "Let's go on a date. I'm free Friday the 13th.",
  },
  {
    id: 7,
    name: "Darth Vader",
    url: "../assets/characters/men/darth.png",
    bio: "If you have a daddy or choking kink, I'm your guy. I have two kids (I hope that's not a deal breaker).",
  },
  {
    id: 8,
    name: "Willy Wonka",
    url: "../assets/characters/men/willy.png",
    bio: "Factory owner seeking someone with a golden ticket to my heart. No Oompa Loompas please.",
  },
  {
    id: 9,
    name: "Walter White",
    url: "../assets/characters/men/walter.png",
    bio: "Chemist by trade, but now looking for a partner in crime (figuratively speaking, of course).",
  },
  {
    id: 10,
    name: "Latrell Spencer",
    url: "../assets/characters/men/latrell.png",
    bio: "Looking for someone who's not afraid to belt out 'A Thousand Miles' with me during car rides.",
  },
  {
    id: 11,
    name: "Charlie Harper",
    url: "../assets/characters/men/charlie.png",
    bio: "I never know what's going to happen next. I've been married, divorced, and engaged multiple times. But despite all that, I still believe in love, and I'm not giving up on finding my soulmate. Swipe right if you're ready for a little bit of chaos.",
  },
  {
    id: 12,
    name: "Buddy Hobbs",
    url: "../assets/characters/men/buddy.png",
    bio: "Greetings, it's Buddy the Elf. I'm not your average elf, I'm 6'3. Looking for someone who won't judge me for eating spaghetti with maple syrup.",
  },
  {
    id: 13,
    name: "Edward Scissorhands",
    url: "../assets/characters/men/edward.png",
    bio: "Single and ready to carve my way into your heart. Seeking someone who can appreciate my unique talents and isn't afraid of a little sharpness. (I'm not a fan of holding hands, sorry).",
  },
  {
    id: 14,
    name: "Morpheus",
    url: "../assets/characters/men/morpheus.png",
    bio: "Swiping right on me is like taking the red pill, it'll open your eyes to a whole new world.",
  },
  {
    id: 15,
    name: "Elliot Alderson",
    url: "../assets/characters/men/elliot.png",
    bio: "I may have a split personality, but at least one of them is into you.",
  },
  {
    id: 16,
    name: "Dwight Schrute",
    url: "../assets/characters/men/dwight.png",
    bio: "Beet farmer, assistant regional manager, black belt in karate, volunteer sheriff's deputy, and martial arts enthusiast. Seeking a partner who can appreciate my love for beets, and Battlestar Galactica.",
  },
  {
    id: 17,
    name: "Gregory House",
    url: "../assets/characters/men/house.png",
    bio: "My cane is a conversation starter. Want to know the story behind it?",
  },
  {
    id: 18,
    name: "Theodore Lasso",
    url: "../assets/characters/men/ted.png",
    bio: "American football coach turned British soccer coach. I believe in the power of positivity, teamwork, and a good cup of tea.",
  },
];

export const womenCharacter = [
  {
    id: 0,
    name: "Daenerys Targaryen",
    url: "../assets/characters/women/daenerys.png",
    bio: "I am Daenerys Stormborn of the House Targaryen, First of Her Name, the Unburnt, Queen of the Andals and the First Men, Khaleesi of the Great Grass Sea, Breaker of Chains, and Mother of Dragons.",
  },
  {
    id: 1,
    name: "Meredith Gray",
    url: "../assets/characters/women/meredith.png",
    bio: "I know my way around a heart (literally), but I'm still trying to figure out this whole dating thing.",
  },
  {
    id: 2,
    name: "Michonne Hawthorne",
    url: "../assets/characters/women/michonne.png",
    bio: "I may look tough on the outside, but I'm a softie at heart. Swipe right if you're looking for someone who can kick butt and cuddle.",
  },
  {
    id: 3,
    name: "Samara Morgan",
    url: "../assets/characters/women/samara.png",
    bio: "If you're looking for someone who can give you goosebumps with just one phone call, swipe right.",
  },
  {
    id: 4,
    name: "Eleanor Shellstrop",
    url: "../assets/characters/women/eleanor.png",
    bio: "I may not be a saint, but I'm not exactly a demon either.",
  },
  {
    id: 5,
    name: "Minerva McGonagall",
    url: "../assets/characters/women/minerva.png",
    bio: "If you are a cat person, I'm your gal.",
  },
  {
    id: 6,
    name: "Lois Wilkerson",
    url: "../assets/characters/women/lois.png",
    bio: "Mother of five boys. We'll get along if you let me control your life and admit that I'm always right:)",
  },
  {
    id: 7,
    name: "Harley Quinn",
    url: "../assets/characters/women/harley.png",
    bio: "Not sure if I attract crazy or if I make them crazy.",
  },
  {
    id: 8,
    name: "Angela Martin",
    url: "../assets/characters/women/angela.png",
    bio: "If you're looking for someone who's down to earth, funny, and relatable, you should probably swipe left. But if you're into cats, I'm your girl.",
  },
  {
    id: 9,
    name: "Gloria Delgado",
    url: "../assets/characters/women/gloria.png",
    bio: "Not interested in anyone who takes themselves too seriously or doesn't know how to have fun. If you're down for some salsa dancing, margaritas, and a lot of laughter, let's match.",
  },
  {
    id: 10,
    name: "Hermione Granger",
    url: "../assets/characters/women/hermione.png",
    bio: "If you're looking for someone who can cast a Patronus, solve a riddle, and still have time to discuss social justice issues, let's match. But be warned, I won't tolerate any Death Eater sympathizers or Slytherin elitists.",
  },
  {
    id: 11,
    name: "Katniss Everdeen",
    url: "../assets/characters/women/katniss.png",
    bio: "I'm Katniss, and I'm basically the Girl on Fire. When I'm not taking down tyrants and fighting for freedom, I enjoy reading, hiking, and trying new recipes. Looking for someone who can handle my strong will and my even stronger sense of humor.",
  },
  {
    id: 12,
    name: "Carly Shay",
    url: "../assets/characters/women/carly.png",
    bio: "I'm Carly, and I'm a bit of a tech nerd. I love creating content, tinkering with gadgets, and making people laugh.",
  },
  {
    id: 13,
    name: "Mary Jane",
    url: "../assets/characters/women/mary.png",
    bio: "Looking for a guy who can keep up with my love for adventure... and won't get jealous if Spider-Man swings by for a visit.",
  },
  {
    id: 14,
    name: "Miranda Priestley",
    url: "../assets/characters/women/miranda.png",
    bio: "I don't have time for mediocrity in the office, and I definitely don't have time for it in my love life. Swipe right if you think you can handle my high standards.",
  },
  {
    id: 15,
    name: "Jess Day",
    url: "../assets/characters/women/jess.png",
    bio: "Looking for someone who can handle my 'adorkable' personality, love for unicorns, and questionable dance moves. If you're up for singing duets with me and watching rom-coms, we might just be a match.",
  },
  {
    id: 16,
    name: "Connie Tucker",
    url: "../assets/characters/women/connie.png",
    bio: "I may be old-fashioned, but I still know how to have a good time. Looking for a man who can keep up with my spunk and wit.",
  },
  {
    id: 17,
    name: "Elle Woods",
    url: "../assets/characters/women/elle.png",
    bio: "I'm a Harvard Law graduate, but don't worry, I won't judge you for not being as smart as me. Just kidding, I'm not that kind of lawyer. Looking for someone who can appreciate my passion for justice and my ability to look fabulous in any situation.",
  },
];
